name: Setup Node
description: Setup node with pnpm and optional authentication

inputs:
  install:
    description: Install dependencies by default
    required: false
    default: "false"
  node_version:
    description: Node.js version
    required: false
    default: "22"
  pnpm_version:
    description: pnpm version
    required: false
    default: "10.17.1"

runs:
  using: composite
  steps:
    - name: Authenticate (optional)
      if: ${{ inputs.workload_identity_provider != '' && inputs.service_account != '' }}
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ inputs.workload_identity_provider }}
        service_account: ${{ inputs.service_account }}

    - uses: pnpm/action-setup@v4
      with:
        version: ${{ inputs.pnpm_version }}
        run_install: false

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node_version }}
        cache: pnpm
      env:
        NODE_OPTIONS: --max_old_space_size=4096

    - name: Install dependencies
      if: ${{ inputs.install == 'true' }}
      shell: bash
      run: pnpm install --frozen-lockfile
